
export const capitalizeFirstLetter =(str:string):string=> {
  if (!str) { 
    return '';
  }
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
}

export const formatDate =(dateFromDB:string):string =>{
  const dateObject: Date = new Date(dateFromDB);

  const formatter = new Intl.DateTimeFormat('en-GB', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      timeZone: 'Israel' 
  });
  const formattedDate: string = formatter.format(dateObject);
  return formattedDate
}

//MAKE A HELPER FUNTION HERE !!!!!!
// Assuming your current date string is 'DD/MM/YYYY'
// const ddMMyyyyDate:string= "20/12/2025"; 

// Split, reverse to get YYYY, MM, DD, and join with '-'
// const isoDate:string = ddMMyyyyDate.split('/').reverse().join('-'); 
// isoDate will be "2025-12-20"

export function getDaysUntil(futureDateString: string): number {
    // Check if the input string is valid before proceeding
    if (!futureDateString) {
        console.error("Error: Future date string cannot be empty.");
        return 0;
    }
    // Define the number of milliseconds in a day
    const MS_PER_DAY = 1000 * 60 * 60 * 24;
    // 1. Convert the input string to a Date object
    const inputDate = new Date(futureDateString);
    // Check for invalid date conversion
    if (isNaN(inputDate.getTime())) {
        console.error(`Error: Invalid date format provided: ${futureDateString}`);
        return 0;
    }
    // 2. Get today's date and normalize it to midnight (00:00:00)
    const today = new Date();
    // This removes the time component, making the comparison accurate on a day-by-day basis.
    today.setHours(0, 0, 0, 0);
    // 3. Normalize the future date to midnight
    // We create a new date object for the future date and also reset its time.
    const normalizedFutureDate = new Date(inputDate);
    normalizedFutureDate.setHours(0, 0, 0, 0);
    // 4. Calculate the difference in milliseconds
    const timeDifference = normalizedFutureDate.getTime() - today.getTime();
    // 5. Convert the difference to full days
    // Math.floor ensures we only count full, complete 24-hour periods that make up a day.
    const dayDifference = Math.floor(timeDifference / MS_PER_DAY);
    // Return the result, ensuring it is not negative (if the date is in the past)
    return Math.max(0, dayDifference);
}

export const craneOperatorTips = [
    "Always perform a thorough pre-operation inspection before starting work.",
    "Verify the ground conditions are stable and level before setting up the crane.",
    "Check the load chart carefully; never exceed the crane's rated capacity.",
    "Maintain three points of contact when climbing onto or descending from the crane.",
    "Communicate clearly and effectively with the signalperson at all times.",
    "Keep the load as low to the ground as safely possible during travel and swing.",
    "Beware of power lines; maintain the required safe approach distance.",
    "Center the load directly under the main boom tip before making a lift.",
    "Use the correct sling and rigging gear, ensuring they are free from damage.",
    "Avoid shock loading by starting and stopping movements smoothly and gradually.",
    "Familiarize yourself with emergency shutdown procedures and locations.",
    "Be mindful of wind speed and follow all manufacturer derating guidelines.",
    "Always verify the load weight before attempting any lift.",
    "Ensure outriggers are fully extended and properly set on mats or cribbing.",
    "Never leave a suspended load unattended for any reason.",
    "Keep the operator's cabin clean and free of loose debris that could distract you.",
    "Review the lift plan and hazard analysis before every critical lift.",
    "Watch the hoist rope for signs of wear, fraying, or kinking.",
    "Test the brakes and control functions with a small test lift first.",
    "Keep bystanders and non-essential personnel clear of the swing radius.",
    "Use taglines to control the load's movement and prevent spinning.",
    "Understand the stability quadrant and leverage principles of your machine.",
    "During blind lifts, rely completely on clear, standardized hand signals.",
    "Never modify safety features or override system limits.",
    "Check fluid levels and look for leaks before every shift.",
    "Monitor the load indicator closely throughout the entire lift process.",
    "Know the maximum boom angle and radius for the load you are lifting.",
    "When traveling, secure the boom and hook block properly.",
    "Protect the hoist line from damage by sharp edges on the load.",
    "Ensure all safety pins and locking devices are securely in place.",
    "Never operate a crane while fatigued or under the influence of any substance.",
    "Be aware of changing weather conditions, especially sudden fog or rain.",
    "Practice using two-block prevention systems and anti-collision devices.",
    "Before raising the load, check the path for overhead obstructions.",
    "Report any damage or malfunctioning equipment immediately to supervision.",
    "Luffing movements should be slow and deliberate when under load.",
    "Always perform a boom length and angle check against the load chart.",
    "When working near water, be mindful of changing tide or bank stability.",
    "Ensure the boom hoist limits and travel limits are functional.",
    "Properly store all rigging after use to prevent damage and loss.",
    "Always look in the direction of crane movement during travel and swing.",
    "If in doubt about a lift, stop the operation and seek clarification.",
    "Understand the difference between structural capacity and stability capacity.",
    "Avoid swinging the boom over workers or busy areas whenever possible.",
    "Make certain all locking devices on the hook block are engaged.",
    "Verify the signalperson is certified and positioned for clear visibility.",
    "When operating a telescoping boom, keep sections evenly lubricated.",
    "Never use the crane to pull or drag a load horizontally; lift vertically.",
    "Check tire pressure and condition on mobile cranes daily.",
    "Communicate the weight and lift radius to all ground crew members.",
    "Keep your focus inside the exclusion zone and on the load.",
    "Use cribbing under outrigger pads to distribute pressure on soft ground.",
    "Verify the anti-two-block sensor is working correctly before the first lift.",
    "When lowering the load, control the speed to prevent jarring or bouncing.",
    "Regularly clean the windows and mirrors for optimal visibility.",
    "Know where the nearest fire extinguisher is located.",
    "Be patient; rushing a lift greatly increases the chance of an accident.",
    "Only use hand signals if radio communication fails or is unreliable.",
    "Check for nearby excavations that could compromise ground stability.",
    "Ensure counterweights are correctly installed for the planned lift configuration.",
    "Before lifting, ensure the rigging does not foul any part of the crane structure.",
    "Always wear your seatbelt while operating the crane.",
    "Practice smooth, overlapping control movements instead of jerky inputs.",
    "When lowering the boom, watch the load radius carefully.",
    "Verify the condition and tightness of all pins and bolts on the boom.",
    "Keep the crane level indicator in view and correct any tilt promptly.",
    "When operating multiple cranes, establish clear communication protocols.",
    "Avoid sudden stops that can cause the load to swing violently.",
    "Always retract the boom fully before traveling long distances.",
    "Secure the hook block to a designated tie-down point when leaving the crane.",
    "Check the load chart for deductions based on attachments like jibs.",
    "Ensure all lights and warning devices on the crane are operational.",
    "Never allow anyone to ride on the load or the hook block.",
    "If visibility is poor, rely on a dedicated spotter for guidance.",
    "When parking the crane, set the brakes and use wheel chocks.",
    "Keep the hoist drum free of excessive rope piling or crossing.",
    "Verify that the load is balanced before lifting it clear of the ground.",
    "Take short breaks to maintain focus during long shifts.",
    "Before luffing, check that the hook block has sufficient clearance.",
    "Know the location of all underground utilities in the work area.",
    "Only use certified and inspected rigging equipment.",
    "Ensure proper ventilation when operating in enclosed spaces.",
    "Always check the load chart for gross versus net load capacities.",
    "Be aware of the tail swing radius, especially in confined areas.",
    "Never attempt to free a snagged or frozen load by yanking the boom.",
    "When booming down, be cautious of exceeding the maximum radius.",
    "Use a qualified person to inspect all running lines regularly.",
    "Before any lift, estimate the required clearance height.",
    "Avoid side loading the boom unless specifically permitted by the manufacturer.",
    "Verify that the safety latch on the hook is fully operational.",
    "In windy conditions, use a shorter boom and larger radius whenever possible.",
    "Always follow the crane manufacturer's instruction manual.",
    "Check the condition of the engine and hydraulic hoses regularly.",
    "Ensure the communication radio battery is charged before starting the shift.",
    "Maintain a clear path for the load throughout the entire lift arc.",
    "Use a checklist for every setup and teardown procedure.",
    "When operating a lattice boom, watch for loose lacing or chord damage.",
    "Never rely solely on limit switches; be aware of your boom and hook position.",
    "Understand the impact of dynamic loading on the crane structure.",
    "Verify the required minimum radius for the crane configuration.",
    "Always set the parking brake before engaging the $\text{PTO}$ for crane operations.",
    "Check for any temporary ground covers that may shift under load.",
    "Familiarize yourself with specific load handling procedures for your site.",
    "Keep non-essential communication off the main lift channel.",
    "Ensure the load is properly secured before releasing the slings.",
    "Regularly check the tension in the boom pendant ropes.",
    "Be respectful and cooperative with all other crew members.",
    "Monitor the oil pressure and temperature gauges during operation.",
    "Avoid running the engine at maximum $\text{RPM}$ unnecessarily.",
    "When finishing the lift, slowly and deliberately set the load down.",
    "Know the specific weight of all crane attachments and rigging.",
    "Always follow the established signaling and communication protocols.",
    "Check the stability of the load before lifting it completely free.",
    "If the crane shifts or settles, immediately halt the operation.",
    "Maintain situational awareness of all movement around the crane.",
    "Use designated walkways and access points to reach the cab.",
    "Ensure all loose tools are secured in the cab before beginning work.",
    "Be meticulous in logging all operating hours and maintenance actions.",
    "Never adjust safety valves or pressure settings without authorization.",
    "Check that the hoist rope is spooled correctly on the drum.",
    "If a load starts to swing, make small, corrective movements.",
    "Know the emergency procedures for a man basket operation, if applicable.",
    "Always review your performance and look for ways to improve efficiency.",
    "Ensure the load chart inside the cab matches the current crane configuration.",
    "When working at night, verify all work lights provide adequate illumination.",
    "Check that the hook block is traveling smoothly along the line.",
    "Be aware of noise levels that may affect communication.",
    "Practice using the foot controls smoothly and precisely.",
    "Never rely on guessing; always confirm the load weight and radius.",
    "When leaving the cab, remove the key and secure the controls.",
    "Monitor the movement of the boom head relative to the load constantly.",
    "Maintain the proper boom angle for load capacity and reach.",
    "Avoid rapid acceleration or deceleration while hoisting a load.",
    "Be particularly cautious during the initial lift-off stage.",
    "Ensure the boom hoist brake is properly adjusted and holding.",
    "Regularly check for signs of fatigue in yourself and your spotter.",
    "Before raising the boom, verify that there are no obstructions in its path.",
    "Know the local regulations and standards governing crane operation.",
    "Always check the wind direction before swinging a large surface area load.",
    "When dismantling, follow the reverse procedure of the setup sequence.",
    "Verify that the hook block is properly seated when stowed.",
    "Use the horn or warning signals to alert workers of impending movement.",
    "Be extra vigilant when lifting loads with an unknown center of gravity.",
    "Check all hydraulic lines for leaks, cuts, or abrasions.",
    "Ensure the lift capacity is adequate for the *total* load, including rigging.",
    "Keep clear of the wire rope during tensioning and spooling.",
    "Always operate within the clearly defined working boundaries.",
    "Understand the effect of slope on the crane's stability and rating.",
    "When $\text{out-of-service}$, secure the boom to prevent unauthorized movement.",
    "Verify the condition of the boom sheaves and replace any worn ones.",
    "Ensure that the load weight is distributed evenly across all lift points.",
    "Never operate the crane if the safety glass is cracked or broken.",
    "Practice emergency procedures regularly with the lift crew.",
    "Check for nearby hazards like temporary structures or scaffolding.",
    "Maintain a detailed log of all maintenance and repair activities.",
    "Always wear your personal protective equipment ($\text{PPE}$).",
    "If you hear unusual noises, stop the operation and investigate immediately.",
    "Know the contact information for emergency services on site.",
    "Ensure the ground crew is trained in proper rigging techniques.",
    "Avoid lifting during electrical storms or heavy precipitation.",
    "Check the condition of the boom section connection pins.",
    "Before swinging the load, ensure the path is clear below the hook.",
    "Use proper hand placement on controls to prevent accidental activation.",
    "Always confirm the destination spot is clear before lowering the load.",
    "Verify that the crane tires are in good condition and correctly inflated.",
    "Familiarize yourself with the machine's $\text{GPS}$ and telematics system.",
    "Never rely on visual estimation alone for critical distances or weights.",
    "Ensure the hook block is fully seated against the two-block warning system.",
    "Practice slow, controlled lowering on the main hoist line.",
    "Verify the load is secure before swinging the boom away from the pickup point.",
    "Keep the operator's manual readily accessible in the cab.",
    "Check that the counterweight bolts are tightened to the correct torque.",
    "Never use defective or uncertified hoist rope.",
    "Know the maximum permissible slew rate for the current load and radius.",
    "Ensure the crane is properly labeled with all safety warnings.",
    "Always consult a specialist for complex or unconventional lifts.",
    "Check the condition of the main hydraulic oil reservoir.",
    "Be cautious of heat buildup in the brakes during repeated heavy lowering.",
    "Use designated lifting points on the load when rigging.",
    "Avoid swinging the boom into the sun or other sources of glare.",
    "Verify the correct number of parts of line are reeved for the lift.",
    "Maintain clear visibility of the entire operational area.",
    "Ensure the load is free from being stuck or frozen to the ground.",
    "Be mindful of the crane's center of gravity when making extreme movements.",
    "Always lower the load slowly just before it touches down.",
    "Check the condition of the slewing ring teeth and lubrication.",
    "Know the weight of the hook block and rigging to calculate the net load.",
    "Avoid running the hoist rope over the main boom structure.",
    "Ensure the $\text{A/C}$ or heating unit is working to maintain focus and comfort.",
    "When lowering into a pit, communicate clearly with personnel below.",
    "Check that the outrigger indicator lights are functioning correctly.",
    "Never exceed the maximum permissible boom length for your setup.",
    "Familiarize yourself with the controls for emergency power loss.",
    "Always verify the communication method with the rigger before starting.",
    "Ensure the load is stable and balanced before releasing the slings.",
    "Check the boom pin retaining mechanisms for any wear or damage.",
    "Be aware of the effects of thermal expansion on the crane components.",
    "Always use the correct grade of fuel and hydraulic oil.",
    "Keep the main hoist line vertical to prevent lateral loading on the boom.",
    "Check for overhead wires not visible from the cab, like telecom lines.",
    "When working near drop-offs, maintain a safe distance from the edge.",
    "Ensure all access doors and hatches are securely closed before operation.",
    "Never use the crane as a temporary anchor point for other equipment.",
    "Check the condition of the brake pads and discs regularly.",
    "Know the maximum side load that can be applied to the boom tip.",
    "Always maintain a minimum clearance of three feet around the cab.",
    "Verify that the load chart accounts for all counterweight configurations.",
    "Be cautious when lifting loads in congested areas with limited visibility.",
    "Ensure all limit switches are tested at the start of each shift.",
    "Check the condition of the slewing brake and locking mechanism.",
    "Familiarize yourself with the crane's $\text{LMI}$ $\text{system}$ error codes.",
    "Always confirm the load chart reading with the calculated lift parameters.",
    "When operating a tower crane, check the communication line integrity.",
    "Be aware of the maximum permissible ground bearing pressure.",
    "Ensure the outrigger pads are centered under the outrigger floats.",
    "Always consult the chart if changing the boom length mid-lift is necessary.",
    "Check the travel path for any debris or uneven surfaces before moving.",
    "Never attempt to repair complex mechanical failures yourself.",
    "Maintain a safe distance from other operating machinery.",
    "Ensure the rigging is clear of all personal body parts before the lift.",
    "Check the condition of the crane cabin suspension system.",
    "Always use the two-way radio for all critical communication.",
    "Verify that the boom nose is clear of all obstructions before extending.",
    "Be mindful of the wind's effect on the load's swing and stability.",
    "Ensure all safety railings are properly secured before climbing.",
    "Check the calibration date on the $\text{LMI}$ $\text{system}$ display.",
    "Always practice defensive operating techniques.",
    "If a warning light illuminates, stop the operation and investigate promptly.",
    "Know the procedure for switching between main and auxiliary hoists.",
    "Ensure the hydraulic fluid is at the correct operating temperature.",
    "Always secure the hook block at ground level before lowering the boom.",
    "Check the slew ring bearing for any signs of excessive play or noise.",
    "When operating in cold weather, allow ample time for warm-up.",
    "Verify the signalperson is wearing high-visibility clothing.",
    "Never adjust or change the counterweight configuration while loaded.",
    "Check the condition of the pendant ropes on the lattice boom.",
    "Ensure all safety decals are legible and visible.",
    "Always use the outrigger monitoring system to confirm proper setup.",
    "Be aware of the impact of sudden drops in ambient temperature.",
    "Verify the correct boom deflection allowance for the load.",
    "Check the condition of the hoist rope guide rollers.",
    "Never operate a crane that is due for its periodic inspection.",
    "Familiarize yourself with the specific weight of different materials being lifted.",
    "Always check the load radius at the pickup and drop-off points.",
    "Ensure that the communication headset is functioning clearly.",
    "Know the maximum speed for traveling with a suspended load.",
    "Be cautious of slippery surfaces on the crane structure, especially in rain.",
    "Verify the anti-two-block cable is free of kinks or damage.",
    "Always use the appropriate signal for 'Emergency Stop' when necessary.",
    "Check that the $\text{PTO}$ is fully disengaged before driving the crane.",
    "Familiarize yourself with the crane's load sensing device limitations.",
    "Ensure the boom hoist cylinder pins are securely fastened.",
    "Never attach taglines to the crane structure itself.",
    "Check the levelness of the outrigger pads after the load is applied.",
    "Always practice proper housekeeping in the operator's cab.",
    "Verify the capacity of any auxiliary sheave being used.",
    "Be aware of the swing speed to prevent excessive load momentum.",
    "Ensure the hydraulic oil filter is clean and functional.",
    "Never operate a crane without current certification.",
    "Check the condition of the boom tip lights for nighttime operations.",
    "Always maintain clear line-of-sight with the signalperson or load.",
    "Familiarize yourself with the machine's maintenance schedule.",
    "Ensure the outrigger pins are fully seated and locked.",
    "Never allow unauthorized personnel near the crane controls.",
    "Check the integrity of the ground under all outrigger placements.",
    "Be cautious when lifting loads through narrow openings.",
    "Always verify the load drop point is clear of personnel and hazards.",
    "Familiarize yourself with the controls before operating an unfamiliar crane.",
    "Ensure the crane's $\text{LMI}$ $\text{system}$ is configured for the current boom length.",
    "Never operate the crane if the safety lockouts are active or tampered with.",
    "Check the condition of the boom support pads when lowered.",
    "Always use the crane's rated capacity limiter as a guide, not a boundary.",
    "Be aware of the potential for the load to spin in a high wind.",
    "Ensure the counterweight is secured before slewing the boom.",
    "Never stand or walk under a suspended load.",
    "Check the integrity of the hydraulic reservoir pressure cap.",
    "Always use slow, deliberate movements when adjusting the boom angle.",
    "Familiarize yourself with the load chart's fine print and footnotes.",
    "Ensure all personnel are clear before raising or lowering the boom.",
    "Never side-load the boom tip, even without a heavy load.",
    "Check the tightness of all lug nuts on mobile crane wheels.",
    "Always set the brakes and lock the slew before leaving the cab momentarily.",
    "Be aware of any changes in the ground noise during operation.",
    "Ensure the correct type of wire rope is installed on the hoist.",
    "Never use the boom to push or pull materials on the ground.",
    "Check the condition of the taglines before starting the lift.",
    "Always confirm the next movement with the signalperson before executing.",
    "Familiarize yourself with the different hoist speeds available.",
    "Ensure the crane is properly grounded when working near power sources.",
    "Never rely on others to maintain your personal safety.",
    "Check the levelness of the crane throughout the lift operation.",
    "Always keep the load as close to the crane as possible for stability.",
    "Be aware of the pendulum effect and dampen load swing quickly.",
    "Ensure all warning horns and lights are clearly audible and visible.",
    "Never operate the crane with damaged or missing safety guards.",
    "Check the condition of the hoist motor and gearbox for unusual sounds.",
    "Always secure the load against movement during transport.",
    "Familiarize yourself with the crane's maximum working height.",
    "Ensure the hoist rope is properly maintained and lubricated.",
    "Never use the limit switches as a regular means of stopping the load.",
    "Check the load chart for reductions based on cold or hot weather.",
    "Always maintain a minimum distance from other lifting equipment.",
    "Be aware of the possibility of ground subsidence after rain.",
    "Ensure the engine coolant level is sufficient before starting.",
    "Never make sharp turns while traveling with a boom extended.",
    "Check the function of the secondary brake system regularly.",
    "Always confirm the total load weight, including the spreader bar, if used.",
    "Familiarize yourself with the $\text{LMI}$ $\text{system}$ overrides and their proper use.",
    "Ensure the swing brake holds the boom steady during lifts.",
    "Never lift a load if the visibility of the signalperson is obstructed.",
    "Check the outrigger floats for damage or uneven wear.",
    "Always use a checklist to ensure all pre-lift tasks are completed.",
    "Be aware of any overhead wires that sag or move in the wind.",
    "Ensure the load is lifted vertically without horizontal drag.",
    "Never operate a crane that is not $\text{OSHA}$ compliant.",
    "Check the integrity of all $\text{Clevis}$ pins and securing clips.",
    "Always confirm the boom tip height before lifting into the air space.",
    "Familiarize yourself with the specific lift plan documentation.",
    "Ensure the crane's fire suppression system is charged and ready.",
    "Never attempt to lift a load that is partially buried or stuck.",
    "Check the load chart for deductions when working on rubber tires.",
    "Always maintain a professional and focused attitude.",
    "Be aware of all workers inside the crane's potential falling object zone.",
    "Ensure the main $\text{PTO}$ engagement lever is fully locked.",
    "Never use the crane to lift personnel unless it is specifically designed for it.",
    "Check the integrity of the boom sections for cracks or dents.",
    "Always confirm the load radius measurement is accurate.",
    "Familiarize yourself with the maximum permissible wind speed for operation.",
    "Ensure the cab door is properly latched during operation.",
    "Never operate the crane if the $\text{LMI}$ $\text{system}$ is malfunctioning.",
    "Check the condition of all electrical wiring and connections.",
    "Always confirm the hoist drum rotation direction matches the control input.",
    "Be aware of the crane's blind spots and use mirrors effectively.",
    "Ensure the boom hoist pump is operating efficiently and quietly.",
    "Never start an operation without the required safety briefing.",
    "Check the fluid level in the hydraulic power steering system.",
    "Always use the designated tie-off points when working at height on the crane.",
    "Familiarize yourself with the procedure for lowering a load in a blackout.",
    "Ensure the ground under the outriggers will not soften during the lift.",
    "Never rely on ropes or chains that are not officially rated for rigging.",
    "Check the counterweight seating for any movement or play.",
    "Always maintain control of the load during the entire lift sequence.",
    "Be aware of any unusual vibrations during slewing or booming.",
    "Ensure the load chart includes all boom and jib extensions.",
    "Never operate a crane with contaminated hydraulic fluid.",
    "Check the condition of the brake lines and connections.",
    "Always use a qualified rigger to attach and detach the load.",
    "Familiarize yourself with the crane's maximum travel speed under load.",
    "Ensure the safety valve on the hydraulic system is intact.",
    "Never rush the setting of outriggers; stability is paramount.",
    "Check the boom nose pulley sheaves for free rotation.",
    "Always verify the load clearance before making any horizontal movement.",
    "Be aware of the $\text{dynamic}$ forces created by swinging the boom.",
    "Ensure the load's center of gravity is known and accounted for.",
    "Never operate near high-frequency radio transmitters without permission.",
    "Check the integrity of all locking pins on the counterweight system.",
    "Always use the correct $\text{PPE}$ including a hard hat and safety glasses.",
    "Familiarize yourself with the process for replacing the hoist rope.",
    "Ensure the control levers return to neutral when released.",
    "Never operate the crane if you feel unwell or overly tired.",
    "Check the condition of the slew ring bolts for proper torque.",
    "Always confirm the load weight with the lift supervisor.",
    "Be aware of the effects of temperature extremes on crane performance.",
    "Ensure the crane is properly chocked when parked on a slope.",
    "Never rely on a makeshift or temporary communication system.",
    "Check the hydraulic ram seals for any signs of leakage.",
    "Always use a calibrated scale to verify unknown load weights.",
    "Familiarize yourself with the crane's electrical isolation procedure.",
    "Ensure the boom angle indicator is functioning accurately.",
    "Never operate a crane beyond its designed wind-load rating.",
    "Check the condition of the engine air intake filter.",
    "Always confirm the load height before lifting over obstacles.",
    "Be aware of the risk of two-blocking when lowering the boom.",
    "Ensure the cab windows are clean and scratch-free for clear visibility.",
    "Never operate the crane if visibility is severely restricted by fog or dust.",
    "Check the load chart for reduced capacity in certain quadrants.",
    "Always verify the communication channel is clear of interference.",
    "Familiarize yourself with the emergency lowering procedure for the boom.",
    "Ensure the load is not spinning before beginning the hoist.",
    "Never exceed the rated line pull of the hoist rope.",
    "Check the condition of the hoist rope lubrication.",
    "Always maintain a safe distance from other suspended loads.",
    "Be aware of the crane's limits when operating on uneven terrain.",
    "Ensure the crane's logbook is updated after every shift.",
    "Never use the crane to lift loads that are not safely rigged.",
    "Check the tightness of the bolts securing the boom sections.",
    "Always confirm the lift height and radius before engaging the hoist.",
    "Familiarize yourself with the crane's maintenance access points.",
    "Ensure the anti-two-block system is not bypassed or disabled.",
    "Never operate a crane that has an unexplained mechanical fault.",
    "Check the function of the boom extension sequence valves.",
    "Always use the established safety zones around the crane.",
    "Be aware of the effect of centrifugal force during fast slewing.",
    "Ensure the load is properly guided by taglines during placement.",
    "Never leave the crane running unattended.",
    "Check the boom angle sensor for accuracy before the lift.",
    "Always confirm the load chart reading matches the current reeving.",
    "Familiarize yourself with the crane's battery shut-off switch.",
    "Ensure the load is completely free before moving the crane.",
    "Never operate the crane during severe and unpredictable weather changes.",
    "Check the condition of the cab steps and handrails.",
    "Always use the crane's $\text{LMI}$ $\text{system}$ to calculate the maximum safe radius.",
    "Be aware of the crane's tail swing when operating in tight spaces.",
    "Ensure the boom stop limit switch is functioning correctly.",
    "Never rely on the lift $\text{supervisor's}$ word over the load chart.",
    "Check the operation of the $\text{LMI}$ $\text{system}$ display backlight.",
    "Always confirm the load capacity for the maximum boom extension.",
    "Familiarize yourself with the crane's designated refueling procedure.",
    "Ensure the boom head is not obstructed when swinging.",
    "Never operate the crane if the safety signs are missing.",
    "Check the condition of the hydraulic oil cooling fan.",
    "Always use the correct gear for ascending or descending slopes.",
    "Be aware of the crane's tipping point and stability margin.",
    "Ensure the load is evenly balanced and secure in the slings.",
    "Never operate a crane that has been subjected to a lightning strike.",
    "Check the load chart for capacity when using a quick-reeve block.",
    "Always confirm the load's dimensions and shape before the lift.",
    "Familiarize yourself with the crane's emergency brake location.",
    "Ensure the ground crew understands the signalperson's instructions.",
    "Never operate the crane outside its specified temperature range.",
    "Check the boom luffing cable tension on the lattice boom.",
    "Always use the designated communication channel for lift operations.",
    "Be aware of the risk of structural failure from exceeding limits.",
    "Ensure the boom extension indicator is clearly visible from the cab.",
    "Never attempt a lift that you are not fully trained to perform.",
    "Check the condition of the outrigger pad retaining chains.",
    "Always confirm the correct counterweight position for the lift.",
    "Familiarize yourself with the procedure for emergency cab escape.",
    "Ensure the load is free from debris that could fall during the hoist.",
    "Never make rapid adjustments to the control settings.",
    "Check the hydraulic pressure gauges for normal operating range.",
    "Always use clear and standard hand signals when communicating.",
    "Be aware of the effects of sudden $\text{load}$ release on the boom.",
    "Ensure the crane is positioned optimally to minimize swing distance.",
    "Never rely on the hoist rope for a secondary safety tie-off.",
    "Check the boom extension cables for tension and wear.",
    "Always confirm the lift is properly coordinated with all workers.",
    "Familiarize yourself with the crane's daily inspection checklist.",
    "Ensure the crane's hydraulic tank breather is clean.",
    "Never operate a crane if the engine is overheating.",
    "Check the load chart for reduced capacity when using a swing-away jib.",
    "Always maintain a safe zone of operation around the load.",
    "Be aware of the boom deflection under maximum load conditions.",
    "Ensure the hook block is traveling freely without obstruction.",
    "Never attempt to compensate for poor rigging with crane speed.",
    "Check the integrity of the crane's suspension locking system.",
    "Always confirm the boom angle with the $\text{LMI}$ $\text{system}$ reading.",
    "Familiarize yourself with the crane's weight distribution for travel.",
    "Ensure the ground crew is clear before engaging the $\text{PTO}$.",
    "Never operate the crane if the outriggers are not fully extended.",
    "Check the condition of the boom hoist limit sensor.",
    "Always use the main hoist for heavy loads unless directed otherwise.",
    "Be aware of the potential for rope fouling during multi-part reeving.",
    "Ensure the load is secured against wind before lifting in high gusts.",
    "Never make a critical lift without a complete pre-lift meeting.",
    "Check the condition of the slewing ring lubrication system.",
    "Always confirm the boom length is correct before calculating capacity.",
    "Familiarize yourself with the crane's maximum working pressure.",
    "Ensure the load is lifted smoothly from the ground to prevent shock load.",
    "Never operate the crane with an unsecured or loose counterweight.",
    "Check the boom section interlocks for proper engagement.",
    "Always use a load cell to verify the weight of critical lifts.",
    "Be aware of the crane's stability when the boom is fully extended.",
    "Ensure the hoist drum brake is released slowly and deliberately.",
    "Never operate the crane while distracted by a phone or other device.",
    "Check the condition of the outrigger control valves for leaks.",
    "Always confirm the load path is clear of all structures and wires.",
    "Familiarize yourself with the crane's required shutdown procedure.",
    "Ensure the load is securely landed and unrigged before moving the crane.",
    "Never use the crane to pull a rope or chain that is under tension.",
    "Check the hydraulic fluid level while the engine is running.",
    "Always use the lowest possible hoist speed for precise positioning.",
    "Be aware of the crane's stability limits when traveling with a load.",
    "Ensure the boom hoist piston rods are clean and undamaged.",
    "Never operate the crane if the load chart is missing or illegible.",
    "Check the condition of the boom angle indicator display screen.",
    "Always confirm the communication is clear before every movement.",
    "Familiarize yourself with the crane's fuel tank capacity and range.",
    "Ensure the ground crew is trained in proper hand signaling.",
    "Never lift a load over a public road without proper traffic control.",
    "Check the tightness of the bolts holding the cab in place.",
    "Always use the correct $\text{PPE}$ for the specific task and environment.",
    "Be aware of the risk of the load swinging back towards the crane.",
    "Ensure the boom lights are functioning for early morning or late evening work.",
    "Never operate the crane if the ground is visibly soft or unstable.",
    "Check the load chart for deductions when working near obstacles.",
    "Always confirm the load weight with the $\text{LMI}$ $\text{system}$ before lifting.",
    "Familiarize yourself with the crane's emergency fire procedures.",
    "Ensure the boom is properly seated on the rest when stowed.",
    "Never exceed the lateral load capacity of the boom or jib.",
    "Check the condition of the outrigger hydraulic lock valves.",
    "Always use a clear, concise, and professional tone on the radio.",
    "Be aware of the effects of extreme cold on metal fatigue.",
    "Ensure the load is properly seated on the ground before releasing the tension.",
    "Never operate the crane if the two-block warning alarm is disabled.",
    "Check the condition of the hoist rope drum flanges.",
    "Always confirm the sling angles are safe and accounted for.",
    "Familiarize yourself with the crane's electrical system protection.",
    "Ensure the load is stable before the signalperson gives the hoist signal.",
    "Never operate a crane with known defects or damage.",
    "Check the integrity of all $\text{Clevis}$ pins on the boom structure.",
    "Always use the designated parking area for the crane.",
    "Be aware of the risk of boom collapse from excessive side loading.",
    "Ensure the boom extension telescope sections are clean and lubricated.",
    "Never use the crane to deliberately shake or vibrate the load.",
    "Check the load chart for reduced capacity when using a lattice jib.",
    "Always confirm the lift plan includes a clear description of the load.",
    "Familiarize yourself with the crane's maximum $\text{PTO}$ operating time.",
    "Ensure the load is lifted vertically without dragging across surfaces.",
    "Never operate the crane if the hydraulic fluid is visibly dirty or low.",
    "Check the tightness of the hydraulic line fittings on the boom.",
    "Always use the correct type of lubricant for the hoist rope.",
    "Be aware of the potential for static electricity discharge from the load.",
    "Ensure the crane's load indicator is calibrated regularly.",
    "Never operate a crane that has not been recently inspected by a competent person.",
    "Check the condition of the boom hoist limit switch wiring.",
    "Always confirm the load is clear of all rigging before unhooking.",
    "Familiarize yourself with the crane's emergency stopping distance.",
    "Ensure the ground crew maintains a clear view of the signalperson.",
    "Never make a lift if the ground pressure exceeds the soil rating.",
    "Check the function of the main hoist drum rotation indicator.",
    "Always use the $\text{LMI}$ $\text{system}$ to verify the load radius and weight.",
    "Be aware of the crane's swing speed and proximity to other obstacles.",
    "Ensure the load is properly secured before the lift is complete."
];